# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# 
# >> macros
# << macros

Name:       xorg-x11-proto-fontsproto
Summary:    X.Org X11 Protocol fontsproto
Version:    2.0.2
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/fontsproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-fontsproto.yaml
Provides:   fontsproto

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
Description: %{summary}



%prep
%setup -q -n fontsproto-%{version}
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/fontsproto.pc
%{_includedir}/X11/fonts/fsmasks.h
%{_includedir}/X11/fonts/FS.h
%{_includedir}/X11/fonts/fontstruct.h
%{_includedir}/X11/fonts/font.h
%{_includedir}/X11/fonts/fontproto.h
%{_includedir}/X11/fonts/FSproto.h
# << files


